steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/banking-pipeline-4x9k/banking-pipeline/extract:latest', '.']
images:
  - 'europe-west2-docker.pkg.dev/banking-pipeline-4x9k/banking-pipeline/extract:latest'
options:
  logging: CLOUD_LOGGING_ONLY
